#!/bin/sh
mod="Mod1"

riverctl attach-mode bottom
riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-output-change

pkill dbus-river-environment
riverctl spawn 'dbus-river-environment'
pkill configure-gtk
riverctl spawn 'configure-gtk'
pkill swaybg
riverctl spawn 'swaybg -i "$(find ~/.config/nix/wallpapers/c -type f | shuf -n1)" -m fill'
pkill footserver
riverctl spawn 'foot --server --log-no-syslog'

riverctl xcursor-theme 'Adwaita'

riverctl map normal $mod Return spawn 'footclient'
riverctl map normal $mod+Shift s spawn 'pkill slurp || riverctl spawn "grimshot --notify copy area | -"'
riverctl map normal $mod+Shift c spawn 'wl-color-picker clipboard'
riverctl map normal $mod c spawn 'riverctl spawn "google-chrome"'
riverctl map normal $mod n spawn 'pkill gammastep || riverctl spawn "gammastep -O 4000"'
riverctl map normal $mod+Shift Q exit
riverctl map normal $mod Space spawn 'pkill tofi || riverctl spawn "$(tofi-drun)"'
riverctl map normal $mod+Shift R spawn $XDG_CONFIG_HOME/river/init

# $mod+Q to close the focused view
riverctl map normal $mod Q close

# $mod+J and $mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# $mod+Shift+J and $mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# $mod+Period and $mod+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# $mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# $mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod+Shift Return zoom

# $mod+H and $mod+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

# $mod+Shift+H and $mod+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

# $mod+$mod+{H,J,K,L} to move views -- cool but I don't use
# riverctl map normal $mod+Control H move left 100
# riverctl map normal $mod+Control J move down 100
# riverctl map normal $mod+Control K move up 100
# riverctl map normal $mod+Control L move right 100

# $mod+$mod+Control+{H,J,K,L} to snap views to screen edges -- cool but I don't use
# riverctl map normal $mod+Control H snap left
# riverctl map normal $mod+Control J snap down
# riverctl map normal $mod+Control K snap up
# riverctl map normal $mod+Control L snap right

# $mod+$mod+Shift+{H,J,K,L} to resize views -- cool but I don't use
# riverctl map normal $mod+Shift H resize horizontal -100
# riverctl map normal $mod+Shift J resize vertical 100
# riverctl map normal $mod+Shift K resize vertical -100
# riverctl map normal $mod+Shift L resize horizontal 100

# $mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# $mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9)
do
  tags=$((1 << ($i - 1)))

  # $mod+[1-9] to focus tag [0-8]
  riverctl map normal $mod $i set-focused-tags $tags

  # $mod+Shift+[1-9] to tag focused view with tag [0-8]
  riverctl map normal $mod+Shift $i set-view-tags $tags

  # $mod+Ctrl+[1-9] to toggle focus of tag [0-8]
  riverctl map normal $mod+Control $i toggle-focused-tags $tags

  # $mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
  riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

riverctl map normal $mod S toggle-float

# $mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# $mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up    send-layout-cmd rivertile "main-location top"
riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
riverctl map normal $mod Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# $mod+F11 to enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough

# $mod+F11 to return to normal mode
riverctl map passthrough $mod F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
  riverctl map $mode None XF86Eject spawn 'eject -T'
  riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -ui 5 && pamixer --get-volume > /tmp/wobpipe'
  riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -ud 5 && pamixer --get-volume > /tmp/wobpipe'
  riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute && ( pamixer --get-mute && echo 0 > /tmp/wobpipe ) || pamixer --get-volume > /tmp/wobpipe'
  riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
  riverctl map $mode None XF86AudioNext  spawn 'playerctl next'
done

# Set background and border color
riverctl border-width 0
riverctl background-color 0x00000000
riverctl border-color-focused 0x00000000
riverctl border-color-unfocused 0x00000000

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
pkill rivertile
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 -main-ratio 0.5 -main-location left
